version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - ../.env
    ports:
      - 5432:5432
    volumes:
      - ../../migration/postgre:/docker-entrypoint-initdb.d

  # app:
  #   build:
  #     context: ..
  #     dockerfile: ./docker/Dockerfile
  #   container_name: bun-hono-app
  #   env_file:
  #     - ../.env
  #   environment:
  #     - DOCKER_ENV=true
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres